#!/bin/bash

LOCKPFX="/net/nas01/Public/"
case "`uname -n|cut -d. -f1`" in
    *-itb) LOCKPFX=${LOCKPFX}itb_;;
esac

## A cron job will detect that this file exists
touch ${LOCKPFX}oasis_update_lock

## Assure the cron job has started
sleep 62

## don't return until the update is complete
while [ -f ${LOCKPFX}oasis_update_in_progress ]; do
    sleep 10
done
