#!/bin/bash
# Install and configure all application software on oasis
# Written by Dave Dykstra 2-26-2015

set -ex

ARCH=`arch`
AUFSRPM=aufs-0.20090202.cvs-6.sl5.src.rpm
CVMFSRELRPM=cvmfs-release-2-4.el5.noarch.rpm
CVMFSVER=2.1.20
CVMFSRPM=cvmfs-$CVMFSVER-1.el5.$ARCH.rpm
CVMFSSERVERRPM=cvmfs-server-$CVMFSVER-1.el5.$ARCH.rpm
CVMFSCONFIGRPM=cvmfs-config-default-1.1-1.noarch.rpm
OASISRPM=oasis-2.0.8-1.osg32.el5.noarch.rpm

PATH="$PATH:/sbin"

# import OSG key but remove its yum repo because it isn't mirrored
rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-OSG
rpm -e osg-release

# download, build, and install aufs
wget -N "http://ftp.scientificlinux.org/linux/scientific/5x/SRPMS/SL/$AUFSRPM"
mkdir -p /usr/src/redhat/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
rpm -i $AUFSRPM
rm $AUFSRPM
# note: the kernel-devel install may not be needed; it's not removed in
#  uninstall but try to install it because it's not guaranteed to be there
yum install -y rpm-build kernel-devel-`uname -r` gcc
rpmbuild -ba --target $ARCH --define "kernel `uname -r`" /usr/src/redhat/SPECS/aufs.spec
rpm -iv /usr/src/redhat/RPMS/$ARCH/*aufs*.rpm

# install aufs postupdate script so it will get rebuilt when kernel is rebuilt
mkdir -p /opt/etc/osupdate.d
cp `dirname $0`/aufs.postupdate /opt/etc/osupdate.d

# install cvmfs
wget -N https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/$CVMFSRELRPM
rpm -i $CVMFSRELRPM
rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-CernVM
rpm -e cvmfs-release
rm $CVMFSRELRPM
wget -N https://ecsft.cern.ch/dist/cvmfs/cvmfs-$CVMFSVER/$CVMFSRPM
wget -N https://ecsft.cern.ch/dist/cvmfs/cvmfs-$CVMFSVER/$CVMFSSERVERRPM
wget -N https://ecsft.cern.ch/dist/cvmfs/cvmfs-config/$CVMFSCONFIGRPM
CVRPMS="$CVMFSRPM $CVMFSSERVERRPM $CVMFSCONFIGRPM"
yum -y install $CVRPMS
rm $CVRPMS
cp /etc/cvmfs/keys/opensciencegrid.org/opensciencegrid.org.pub /etc/cvmfs/keys

echo -e "*\t\t-\tnofile\t\t16384" >>/etc/security/limits.conf
ulimit -n 16384
cat >/etc/logrotate.d/oasis <<xEOFx
/var/log/oasis/*.log {
    weekly
    missingok
    notifempty
}
xEOFx
cat >/etc/httpd/conf.d/cvmfs.conf <<"xEOFx"
Listen 8000
KeepAlive On
xEOFx
chkconfig httpd on
service httpd start

cat >/etc/iptables.d/60-local-cvmfs <<"xEOFx"
. /etc/iptables.d/setup
# open tcp port 80 and port 8000
$ITFAI -p tcp --dport 80 -j ACCEPT
$ITFAI -p tcp --dport 8000 -j ACCEPT
$ITFAI4 -p tcp --dport 80 -j ACCEPT
$ITFAI4 -p tcp --dport 8000 -j ACCEPT
xEOFx
chmod +x /etc/iptables.d/60-local-cvmfs
service gociptables restart
mkdir -p /srv

# install oasis
OASISVER="`echo $OASISRPM|cut -d- -f2`"
OASISSUBVER="`echo $OASISRPM|cut -d- -f3|cut -d. -f1-3`"
wget -N http://koji-hub.batlab.org/mnt/koji/packages/oasis/$OASISVER/$OASISSUBVER/noarch/$OASISRPM
yum -y install $OASISRPM
rm $OASISRPM

# need nfslock for the repos to be on NFS
chkconfig nfslock on
service nfslock start

# add oasis repo
SRVDIR="/net/nas01/srv/`uname -n|cut -d. -f1`"
if [ ! -d $SRVDIR ]; then
    mkdir $SRVDIR
    setfacl -b $SRVDIR
    chmod 755 $SRVDIR
    mkdir $SRVDIR/cvmfs
    mkdir $SRVDIR/spool
fi
CVMFS_AUFS_WARNING=false cvmfs_server mkfs -m -o oasis oasis.opensciencegrid.org
echo "CVMFS_AUFS_WARNING=false" >>/etc/cvmfs/repositories.d/oasis.opensciencegrid.org/server.conf
echo "CVMFS_IGNORE_XDIR_HARDLINKS=true" >>/etc/cvmfs/repositories.d/oasis.opensciencegrid.org/server.conf

# move scratch dir and /srv/cvmfs to attached storage
umount /cvmfs/oasis.opensciencegrid.org
rm -rf $SRVDIR/spool/oasis.opensciencegrid.org/scratch
mkdir -p $SRVDIR/spool/oasis.opensciencegrid.org
mv /var/spool/cvmfs/oasis.opensciencegrid.org/scratch $SRVDIR/spool/oasis.opensciencegrid.org
mkdir /var/spool/cvmfs/oasis.opensciencegrid.org/scratch
sed -i -e "/^cvmfs2#oasis/inas01:`echo $SRVDIR|sed 's,/net/nas01,,'`/spool/oasis.opensciencegrid.org/scratch /var/spool/cvmfs/oasis.opensciencegrid.org/scratch nfs defaults 1 2 # added by install-oasis" /etc/fstab
mount /var/spool/cvmfs/oasis.opensciencegrid.org/scratch

umount /var/spool/cvmfs/oasis.opensciencegrid.org/rdonly
if [ -d $SRVDIR/cvmfs/oasis.opensciencegrid.org ]; then
    # old repository data present.  save new one for now.
    rm -rf /srv/cvmfs.save
    mkdir -p /srv/cvmfs.save
    rm -rf /srv/cvmfs.save/oasis.opensciencegrid.org
    mv /srv/cvmfs/oasis.opensciencegrid.org /srv/cvmfs.save
else
    mv /srv/cvmfs/oasis.opensciencegrid.org $SRVDIR/cvmfs
fi
rmdir /srv/cvmfs
ln -s $SRVDIR/cvmfs /srv
mount /var/spool/cvmfs/oasis.opensciencegrid.org/rdonly
mount /cvmfs/oasis.opensciencegrid.org

RUNUSER="runuser -s /bin/bash oasis -c"

if [ -d /srv/cvmfs.save ]; then
    # update the old .cvmfspublished with new certificate hash
    REPONAME=oasis.opensciencegrid.org
    CERTHASH="`cat -v /srv/cvmfs.save/$REPONAME/.cvmfspublished|sed -n 's/^X//p'`"
    $RUNUSER "cd /srv/cvmfs/$REPONAME; cat -v .cvmfspublished | \
	    sed 's/^X.*/X'$CERTHASH'/;/^--/q' > .cvmfspublished.unsigned"
    CERTPATH="`echo $CERTHASH|sed 's,^\(..\),\1/,'`X"
    $RUNUSER "cp /srv/cvmfs.save/$REPONAME/data/$CERTPATH /srv/cvmfs/$REPONAME/data/$CERTPATH"
    UPSTREAM="`sed -n 's/^CVMFS_UPSTREAM_STORAGE=//p' /etc/cvmfs/repositories.d/$REPONAME/server.conf`"
    $RUNUSER "cd /srv/cvmfs/$REPONAME; cvmfs_swissknife sign -c /etc/cvmfs/keys/$REPONAME.crt -k /etc/cvmfs/keys/$REPONAME.key -n $REPONAME -m .cvmfspublished.unsigned -t /var/spool/cvmfs/$REPONAME/tmp -r $UPSTREAM"
    rm -rf /srv/cvmfs.save
    cvmfs_server resign

    # sync up the view in /cvmfs/oasis.opensciencegrid.org with
    #   new underlying data
    $RUNUSER "cvmfs_server transaction"
    $RUNUSER "cvmfs_server publish"
fi

# Manage repository content special content

$RUNUSER "cvmfs_server transaction"

if [ -f /cvmfs/oasis.opensciencegrid.org/new_repository ]; then
    # clean out initial file
    rm /cvmfs/oasis.opensciencegrid.org/new_repository
fi

if [ ! -f /cvmfs/oasis.opensciencegrid.org/.cvmfsdirtab ]; then
    # read in .cvmfsdirtab from subversion
    cd /cvmfs/oasis.opensciencegrid.org
    # svn checkout only works as root, do chown afterward
    svn checkout https://osg-svn.rtinfo.indiana.edu/goc-internal/install/oasis/files/oasis-repo .
    chown -R oasis:oasis .svn .cvmfsdirtab
    cd
fi

if [ ! -L /cvmfs/oasis.opensciencegrid.org/cmssoft/cms ]; then
    # create special cms symlink
    $RUNUSER "mkdir -p /cvmfs/oasis.opensciencegrid.org/cmssoft"
    $RUNUSER "ln -s /cvmfs/cms.cern.ch /cvmfs/oasis.opensciencegrid.org/cmssoft/cms"
fi

if [ ! -L /cvmfs/oasis.opensciencegrid.org/osg-software/osg-wn-client ]; then
    # create special osg-software symlink
    $RUNUSER "mkdir -p /cvmfs/oasis.opensciencegrid.org/osg-software"
    $RUNUSER "ln -s /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client /cvmfs/oasis.opensciencegrid.org/osg-software/osg-wn-client"
fi

sleep 2 # cvmfs-2.1.20 complains if two publishes done in the same second
$RUNUSER "cvmfs_server publish"

# add cron entries
mkdir -p /var/log/oasis
cat >>/etc/cron.d/oasis <<'xEOFx'
* * * * *   root   /usr/share/oasis/do_oasis_update
*/3 * * * * root   /usr/share/oasis/oasis_status_stamp
xEOFx

set +x

# request updates on all vos

LOCKPFX=/net/nas01/Public/
case "`uname -n|cut -d. -f1`" in
    *-itb) LOCKPFX=${LOCKPFX}itb_;;
esac
for VO in `/usr/share/oasis/print_oasis_vonames`; do
    if [ ! -f /net/nas01/Public/ouser.$VO/update.details ]; then
	# skip because it hasn't been published yet
	continue
    fi
    if cmp /net/nas01/Public/ouser.$VO/cvmfs/oasis.opensciencegrid.org/$VO/update.details 2>/dev/null; then
	# already up to date, nothing to do
	continue
    fi
    echo "Requesting update for $VO at `date`"
    echo $VO >${LOCKPFX}vo_update_requested
    # this waits for the request to complete
    /usr/share/oasis/request_oasis_update
done

echo 
echo "Installation of `uname -n|cut -d. -f1` completed successfully at `date`"
