#!/bin/bash
# Uninstall everything installed by install-oasis, to facilitate
#  testing install-oasis without creating a new VM from scratch
# Written by Dave Dykstra 2-26-2015

cd

case "`uname -n`" in
    oasis.*|oasis-itb.*);;
    *)  echo "Only run this on oasis or oasis-itb"
	exit 2
	;;
esac

set -x
PATH="$PATH:/sbin"
rm /etc/cron.d/oasis
killall rsync
killall cvmfs_swissknife
rm /srv/cvmfs
yum -y remove oasis
rm -rf /etc/oasis
cvmfs_server rmfs -f oasis.opensciencegrid.org # removes partially
umount /var/spool/cvmfs/oasis.opensciencegrid.org/scratch
cvmfs_server rmfs -f oasis.opensciencegrid.org # finishes the remove
rm /var/spool/cvmfs
rm -rf /usr/spool/cvmfs
rmdir /usr/spool
sed -i -e '/added by install-oasis/d' /etc/fstab
rm -rf /var/spool/cvmfs/*
rm /opt/etc/osupdate.d/aufs.postupdate
rm -rf /usr/src/redhat/*/aufs* /usr/src/redhat/RPMS/*/*aufs*
rmdir /usr/src/redhat/RPMS/* /usr/src/redhat/* /usr/src/redhat
yum -y remove elfutils-libs xz-libs gcc aufs kernel-module-aufs
rm -rf /var/log/oasis
rm /etc/logrotate.d/oasis
service httpd stop
sed -i -e '/Added by install/d' -e '/^net.core.somaxconn/d' /etc/sysctl.conf
sysctl -w net.core.somaxconn=128
rm -f /var/www/html/stamp
rpm -e cvmfs-release
for r in `rpm -qa|grep gpg-pubkey|sed 's/\.(none)//'|sort -u`; do
    rpm --allmatches -e $r
done
yum -y remove httpd fuse fuse-libs cvmfs-config gdb
sed -i '/nofile.*16384/d' /etc/security/limits.conf
rm -rf /etc/cvmfs
rm /etc/httpd/conf.d/cvmfs.conf
rm /etc/iptables.d/60-local-oasis
service gociptables restart
yum clean all
service nfslock stop
chkconfig nfslock off
