#!/bin/bash
# Uninstall everything installed by install-oasis-replica, to facilitate
#  testing install-oasis-replica without creating a new VM from scratch
# Written by Dave Dykstra 2-4-2015

set -x
PATH="$PATH:/sbin"
killall cvmfs_swissknife
rm /srv/cvmfs
for REPO in `ls /etc/cvmfs/repositories.d`; do
    cvmfs_server rmfs -f $REPO
done
rm /etc/cron.d/cvmfs
rm -rf /var/log/cvmfs
rm /opt/etc/osupdate.d/aufs.postupdate
rm -rf /usr/src/redhat/*/aufs* /usr/src/redhat/RPMS/*/*aufs*
rmdir /usr/src/redhat/RPMS/* /usr/src/redhat/* /usr/src/redhat
yum -y remove elfutils-libs xz-libs gcc aufs kernel-module-aufs
OSGREL=osg-3.1-el5-release-latest.rpm
wget -N http://repo.grid.iu.edu/osg/3.1/$OSGREL
rpm -iv $OSGREL
rm -f $OSGREL
service httpd stop
rpm -e cvmfs-release
rpm -e frontier-release
for r in `rpm -qa|grep gpg-pubkey|sed 's/\.(none)//'|sort -u`; do
    rpm --allmatches -e $r
done
yum -y remove httpd fuse fuse-libs cvmfs-config gdb
sed -i '/nofile.*16384/d' /etc/security/limits.conf
rm /etc/cvmfs/keys/egi.eu.pub /etc/cvmfs/keys/opensciencegrid.org.pub
rm /etc/logrotate.d/cvmfs
rm /etc/httpd/conf.d/cvmfs.conf
yum -y remove frontier-squid
rm /etc/squid/customize.sh.rpmsave
rmdir /etc/squid
rm /etc/iptables.d/60-local-cvmfs
service gociptables restart
yum -y remove oasis
service nfslock stop
chkconfig nfslock off
