#!/bin/bash
# Uninstall everything installed by install-oasis-replica, to facilitate
#  testing install-oasis-replica without creating a new VM from scratch
# Written by Dave Dykstra 2-26-2015

set -x
PATH="$PATH:/sbin"
killall rsync
killall cvmfs_swissknife
rm /srv/cvmfs
cvmfs_server rmfs -f oasis.opensciencegrid.org # removes partially
umount /var/spool/cvmfs/oasis.opensciencegrid.org/scratch
cvmfs_server rmfs -f oasis.opensciencegrid.org # finishes the remove
rm /var/spool/cvmfs
rm -rf /usr/spool/cvmfs
rmdir /usr/spool
sed -i -e '/added by install-oasis/d' /etc/fstab
rm -rf /var/spool/cvmfs/*
rm /etc/cron.d/oasis
rm -rf /var/log/oasis
rm /opt/etc/osupdate.d/aufs.postupdate
rm -rf /usr/src/redhat/*/aufs* /usr/src/redhat/RPMS/*/*aufs*
rmdir /usr/src/redhat/RPMS/* /usr/src/redhat/* /usr/src/redhat
yum -y remove elfutils-libs xz-libs gcc aufs kernel-module-aufs
service httpd stop
rm -f /var/www/html/stamp
rpm -e cvmfs-release
for r in `rpm -qa|grep gpg-pubkey|sed 's/\.(none)//'|sort -u`; do
    rpm --allmatches -e $r
done
yum -y remove httpd fuse fuse-libs cvmfs-config gdb
sed -i '/nofile.*16384/d' /etc/security/limits.conf
rm /etc/cvmfs/keys/opensciencegrid.org.pub
rm /etc/logrotate.d/oasis
rm /etc/httpd/conf.d/cvmfs.conf
rm /etc/iptables.d/60-local-cvmfs
service gociptables restart
yum -y remove oasis
service nfslock stop
chkconfig nfslock off
