#!/bin/bash
# Install and configure all application software on oasis or oasis-itb
# Written by Dave Dykstra 2-26-2015

case "`uname -n`" in
    oasis.*|oasis-itb.*);;
    *)  echo "Only run this on oasis or oasis-itb"
	exit 2
	;;
esac

set -ex

SCRIPTDIR="`dirname $0`"
if [ "$SCRIPTDIR" = "." ]; then
    SCRIPTDIR="`pwd`"
fi
cd

ARCH=`arch`
AUFSRPM=aufs-0.20090202.cvs-6.sl5.src.rpm
CVMFSRELRPM=cvmfs-release-2-4.el5.noarch.rpm
CVMFSVER=2.1.20
CVMFSRPM=cvmfs-$CVMFSVER-1.el5.$ARCH.rpm
CVMFSSERVERRPM=cvmfs-server-$CVMFSVER-1.el5.$ARCH.rpm
CVMFSCONFIGRPM=cvmfs-config-default-1.1-1.noarch.rpm
OASISRPM=oasis-2.0.21-1.osg32.el5.noarch.rpm

PATH="$PATH:/sbin"

# import OSG key because we'll be directly downloading oasis rpm
rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-OSG

# download, build, and install aufs
wget -q -N "http://ftp.scientificlinux.org/linux/scientific/5x/SRPMS/SL/$AUFSRPM"
mkdir -p /usr/src/redhat/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
rpm -i $AUFSRPM
rm $AUFSRPM
# note: the kernel-devel install may not be needed; it's not removed in
#  uninstall but try to install it because it's not guaranteed to be there
yum install -y rpm-build kernel-devel-`uname -r` gcc
rpmbuild -ba --target $ARCH --define "kernel `uname -r`" /usr/src/redhat/SPECS/aufs.spec
rpm -iv /usr/src/redhat/RPMS/$ARCH/*aufs*.rpm

# install aufs postupdate script so it will get rebuilt when kernel is rebuilt
mkdir -p /opt/etc/osupdate.d
cp $SCRIPTDIR/aufs.postupdate /opt/etc/osupdate.d

# install cvmfs
wget -q -N https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/$CVMFSRELRPM
rpm -i $CVMFSRELRPM
rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-CernVM
rpm -e cvmfs-release
rm $CVMFSRELRPM
wget -q -N https://ecsft.cern.ch/dist/cvmfs/cvmfs-$CVMFSVER/$CVMFSRPM
wget -q -N https://ecsft.cern.ch/dist/cvmfs/cvmfs-$CVMFSVER/$CVMFSSERVERRPM
wget -q -N https://ecsft.cern.ch/dist/cvmfs/cvmfs-config/$CVMFSCONFIGRPM
CVRPMS="$CVMFSRPM $CVMFSSERVERRPM $CVMFSCONFIGRPM"
yum -y install $CVRPMS
rm $CVRPMS
cp /etc/cvmfs/keys/opensciencegrid.org/opensciencegrid.org.pub /etc/cvmfs/keys
# move /var/spool/cvmfs to /usr/spool because /var is too small for cache & tmp
rm -rf /usr/spool/cvmfs
mkdir -p /usr/spool
mv /var/spool/cvmfs /usr/spool
ln -s /usr/spool/cvmfs /var/spool

echo -e "*\t\t-\tnofile\t\t16384" >>/etc/security/limits.conf
ulimit -n 16384

# The log rotate file is installed by the RPM
#cat >/etc/logrotate.d/oasis <<xEOFx
## Created by install script.  Will be recreated next reinstall.
#/var/log/oasis/*.log {
#    weekly
#    missingok
#    notifempty
#}
#xEOFx

cat >/etc/httpd/conf.d/cvmfs.conf <<"xEOFx"
# Created by install script.  Will be recreated next reinstall.
Listen 8000
KeepAlive On
MaxClients 64
ListenBackLog 1024
xEOFx
chkconfig httpd on
service httpd start

cat >>/etc/sysctl.conf <<xEOFx
# Controls maximum listen() backlog for apache.  Added by install script.
net.core.somaxconn = 1024
xEOFx
sysctl -w net.core.somaxconn=1024

# add robots.txt
cat >/var/www/html/robots.txt <<xEOFx
User-agent: *
Disallow: /
xEOFx

cat >/etc/iptables.d/60-local-oasis <<"xEOFx"
# Created by install script.  Will be recreated next reinstall.
. /etc/iptables.d/setup
# open tcp port 80 and port 8000
$ITFAI -p tcp --dport 80 -j ACCEPT
$ITFAI -p tcp --dport 8000 -j ACCEPT
$ITFAI4 -p tcp --dport 80 -j ACCEPT
$ITFAI4 -p tcp --dport 8000 -j ACCEPT
xEOFx
chmod +x /etc/iptables.d/60-local-oasis
service gociptables restart
mkdir -p /srv

# install oasis
OASISVER="`echo $OASISRPM|cut -d- -f2`"
OASISSUBVER="`echo $OASISRPM|cut -d- -f3|cut -d. -f1-3`"
wget -q -N http://koji-hub.batlab.org/mnt/koji/packages/oasis/$OASISVER/$OASISSUBVER/noarch/$OASISRPM
yum -y install $OASISRPM
rm $OASISRPM

# need nfslock for the repos to be on NFS
chkconfig nfslock on
service nfslock start

# add oasis repo
SRVDIR="/net/nas01/srv/`uname -n|cut -d. -f1`"
if [ ! -d $SRVDIR ]; then
    mkdir $SRVDIR
    setfacl -b $SRVDIR
    chmod 755 $SRVDIR
    mkdir $SRVDIR/cvmfs
    mkdir $SRVDIR/spool
fi
CVMFS_AUFS_WARNING=false cvmfs_server mkfs -m -o oasis oasis.opensciencegrid.org
echo "CVMFS_AUFS_WARNING=false" >>/etc/cvmfs/repositories.d/oasis.opensciencegrid.org/server.conf
echo "CVMFS_IGNORE_XDIR_HARDLINKS=true" >>/etc/cvmfs/repositories.d/oasis.opensciencegrid.org/server.conf
echo "CVMFS_AUTO_TAG=false" >>/etc/cvmfs/repositories.d/oasis.opensciencegrid.org/server.conf

# move scratch dir and /srv/cvmfs to attached storage
umount /cvmfs/oasis.opensciencegrid.org
rm -rf $SRVDIR/spool/oasis.opensciencegrid.org/scratch
mkdir -p $SRVDIR/spool/oasis.opensciencegrid.org
mv /var/spool/cvmfs/oasis.opensciencegrid.org/scratch $SRVDIR/spool/oasis.opensciencegrid.org
mkdir /var/spool/cvmfs/oasis.opensciencegrid.org/scratch
sed -i -e "/^cvmfs2#oasis/inas01:`echo $SRVDIR|sed 's,/net/nas01,,'`/spool/oasis.opensciencegrid.org/scratch /var/spool/cvmfs/oasis.opensciencegrid.org/scratch nfs defaults 1 2 # added by install-oasis" /etc/fstab
mount /var/spool/cvmfs/oasis.opensciencegrid.org/scratch

umount /var/spool/cvmfs/oasis.opensciencegrid.org/rdonly
if [ -d $SRVDIR/cvmfs/oasis.opensciencegrid.org ]; then
    # old repository data present.  save new one for now.
    rm -rf /srv/cvmfs.save
    mkdir -p /srv/cvmfs.save
    rm -rf /srv/cvmfs.save/oasis.opensciencegrid.org
    mv /srv/cvmfs/oasis.opensciencegrid.org /srv/cvmfs.save
else
    mv /srv/cvmfs/oasis.opensciencegrid.org $SRVDIR/cvmfs
fi
rmdir /srv/cvmfs
ln -s $SRVDIR/cvmfs /srv
mount /var/spool/cvmfs/oasis.opensciencegrid.org/rdonly
mount /cvmfs/oasis.opensciencegrid.org

# on itb install the saved itb pub & master key
case $SRVDIR in
    *-itb)
	if [ ! -f $SRVDIR/etc/cvmfs/oasis-itb.opensciencegrid.org.pub ]; then
	    # make a copy from production srv directory of itb pub and masterkey
	    PRODSRVDIR="`echo $SRVDIR|sed 's/-itb//'`"
	    mkdir -p $SRVDIR/etc/cvmfs
	    cp $PRODSRVDIR/etc/cvmfs/oasis-itb.opensciencegrid.org.* $SRVDIR/etc/cvmfs
	fi
	for KEY in pub masterkey; do
	    cp $SRVDIR/etc/cvmfs/oasis-itb.opensciencegrid.org.$KEY /etc/cvmfs/keys/oasis.opensciencegrid.org.$KEY
	done
	cvmfs_server resign
	;;
esac

RUNUSER="runuser -s /bin/bash oasis -c"

if [ -d /srv/cvmfs.save ]; then
    # update the old .cvmfspublished with new certificate hash
    REPONAME=oasis.opensciencegrid.org
    CERTHASH="`cat -v /srv/cvmfs.save/$REPONAME/.cvmfspublished|sed -n '/^X/{s/^X//p;q}'`"
    $RUNUSER "cd /srv/cvmfs/$REPONAME; cat -v .cvmfspublished | \
	    sed 's/^X.*/X'$CERTHASH'/;/^--/q' > .cvmfspublished.unsigned"
    CERTPATH="`echo $CERTHASH|sed 's,^\(..\),\1/,'`X"
    $RUNUSER "cp /srv/cvmfs.save/$REPONAME/data/$CERTPATH /srv/cvmfs/$REPONAME/data/$CERTPATH"
    UPSTREAM="`sed -n 's/^CVMFS_UPSTREAM_STORAGE=//p' /etc/cvmfs/repositories.d/$REPONAME/server.conf`"
    $RUNUSER "cd /srv/cvmfs/$REPONAME; cvmfs_swissknife sign -c /etc/cvmfs/keys/$REPONAME.crt -k /etc/cvmfs/keys/$REPONAME.key -n $REPONAME -m .cvmfspublished.unsigned -t /var/spool/cvmfs/$REPONAME/tmp -r $UPSTREAM"
    rm -rf /srv/cvmfs.save
    cvmfs_server resign

    # sync up the view in /cvmfs/oasis.opensciencegrid.org with
    #   new underlying data
    $RUNUSER "cvmfs_server transaction"
    $RUNUSER "cvmfs_server publish"
fi

# Manage repository content special content

$RUNUSER "cvmfs_server transaction"

if [ -f /cvmfs/oasis.opensciencegrid.org/new_repository ]; then
    # clean out initial file
    rm /cvmfs/oasis.opensciencegrid.org/new_repository
fi

# make sure there's a .cvmfsdirtab
DIRTAB=$SRVDIR/etc/repo/.cvmfsdirtab
if [ ! -f $DIRTAB ]; then
    case $SRVDIR in
	*-itb)
	    # make a copy from production
	    SRCDIRTAB="`echo $DIRTAB|sed 's/-itb//'`"
	    mkdir -p `dirname $DIRTAB`
	    cp $SRCDIRTAB $DIRTAB
	    ;;
    esac
fi
if [ ! -f /cvmfs/oasis.opensciencegrid.org/.cvmfsdirtab ]; then
    $RUNUSER "cp $DIRTAB /cvmfs/oasis.opensciencegrid.org"
fi

if [ ! -L /cvmfs/oasis.opensciencegrid.org/cmssoft/cms ]; then
    # create special cms symlink
    $RUNUSER "mkdir -p /cvmfs/oasis.opensciencegrid.org/cmssoft"
    $RUNUSER "ln -s /cvmfs/cms.cern.ch /cvmfs/oasis.opensciencegrid.org/cmssoft/cms"
fi

if [ ! -L /cvmfs/oasis.opensciencegrid.org/osg-software/osg-wn-client ]; then
    # create special osg-software symlink
    $RUNUSER "mkdir -p /cvmfs/oasis.opensciencegrid.org/osg-software"
    $RUNUSER "ln -s /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client /cvmfs/oasis.opensciencegrid.org/osg-software/osg-wn-client"
fi

sleep 2 # when auto tagging is on, cvmfs-2.1.20 complains if two publishes done in the same second
$RUNUSER "cvmfs_server publish"

# add cron entries
mkdir -p /var/log/oasis
cat >/etc/cron.d/oasis <<'xEOFx'
# Created by install script.  Will be recreated next reinstall.
* * * * *   root   /usr/share/oasis/do_oasis_update
*/3 * * * * root   /usr/share/oasis/oasis_status_stamp
xEOFx

# request updates on all vos that have changed

LOCKPFX=/net/nas01/Public/
case "`uname -n|cut -d. -f1`" in
    *-itb) LOCKPFX=${LOCKPFX}itb_;;
esac
rm -f ${LOCKPFX}vo_update_requested # sometimes this doesn't get cleaned up
/usr/share/oasis/update_oasis_vos

case "`uname -n|cut -d. -f1`" in
    *-itb) 
	# on itb also update the vos once an hour if they have changed
	cat >>/etc/cron.d/oasis <<xEOFx
1 * * * *   root   /usr/share/oasis/update_oasis_vos >>/var/log/oasis/voupdates.log 2>&1
xEOFx
	;;
esac

# update the publication revision to be 100 greater than the previous revision
PREVREVISION="`wget -qO- http://oasis-replica.opensciencegrid.org:8000/cvmfs/oasis.opensciencegrid.org/.cvmfspublished|cat -v|sed -n '/^S/{s/^S//p;q;}'`"
let PREVREVISION+=100
CURREVISION="`cat -v /srv/cvmfs/oasis.opensciencegrid.org/.cvmfspublished|sed -n '/^S/{s/^S//p;q;}'`"

if [ "$PREVREVISION" -gt "$CURREVISION" ]; then
    $RUNUSER "cvmfs_server transaction"
    $RUNUSER "cvmfs_server publish -n $PREVREVISION"
fi

# -------- BEGIN OASIS-2 SECTION ---------
# install OASIS-2 configuration
# not yet enabled by default, just installed

cat >/etc/oasis/oasis.conf <<xEOFx
# Created by install script.  Will be recreated next reinstall.
[OASIS]

services = server
sleep = 100

#email = 
#SMTPServer

projectsconf = /etc/oasis/projects.conf
repositoriesconf = /etc/oasis/repositories.conf

probesconf = /etc/oasis/probes.conf

flagfilebasedir = /net/nas01/Public/

xEOFx

cat >/etc/oasis/repositories.conf <<xEOFx
# Created by install script.  Will be recreated next reinstall.
[OASIS]

repositoryname = oasis.opensciencegrid.org
distributiontool = cvmfs21
OSG_APP = /net/nas01/Public/
repository_src_dir = %(OSG_APP)s
repository_dest_dir = oasis.opensciencegrid.org
repository_src_owner = root
repository_dest_owner = oasis
xEOFx

# these two are empty for now
touch /etc/oasis/probes.conf
touch /etc/oasis/no_vo_probes.conf

# generate projects.conf now and from cron
python /usr/share/oasis/generate_config_projects > /etc/oasis/projects.conf
cat >>/etc/cron.d/oasis <<xEOFx
2-59/5 * * * * root cd /etc/oasis;if /usr/share/oasis/generate_config_projects > projects.conf.tmp; then if cmp -s projects.conf.tmp projects.conf; then rm projects.conf.tmp; else mv -f projects.conf.tmp projects.conf; /sbin/service oasisd condrestart; fi; fi
xEOFx
# -------- END OASIS-2 SECTION ---------

set +x

# add the signed external repositories whitelists
# this is safer than reading from the original sources, in case one is down
for REPO in `print_osg_repos|grep opensciencegrid.org`; do
    if [ ! -f /srv/cvmfs/$REPO/.cvmfswhitelist ]; then
	URL="http://oasis-replica.opensciencegrid.org:8000/cvmfs/$REPO/.cvmfswhitelist"
	echo "Adding whitelist from $URL"
	mkdir -p /srv/cvmfs/$REPO
	wget -q -O/srv/cvmfs/$REPO/.cvmfswhitelist $URL
    fi
done

echo
echo "Installation of `uname -n|cut -d. -f1` completed successfully at `date`"
echo
case $SRVDIR in
    *-itb);;
    *)  # on prod remove the temporary masterkey and install official public key
	rm /etc/cvmfs/keys/oasis.opensciencegrid.org.masterkey
	cp /etc/cvmfs/keys/opensciencegrid.org.pub /etc/cvmfs/keys/oasis.opensciencegrid.org.pub
	echo "Now temporarily install /etc/cvmfs/keys/oasis.opensciencegrid.org.masterkey"
	echo "   and run resign_osg_whitelist"
esac
