#!/bin/bash
# Uninstall everything installed by install-oasis-login, to facilitate
#  testing install-oasis-login without creating a new VM from scratch
# Written by Dave Dykstra 3-11-2015

case "`uname -n`" in
    oasis-login.*|oasis-login-itb.*);;
    *)  echo "Only run this on oasis-login or oasis-login-itb"
	exit 2
	;;
esac

set -x
PATH="$PATH:/sbin:/usr/sbin"
rm /etc/cron.d/oasis-login
service gsisshd stop
chkconfig gsisshd off
service sshd start
chkconfig sshd on
for r in `rpm -qa|grep gpg-pubkey|sed 's/\.(none)//'|sort -u`; do
    rpm --allmatches -e $r
done
rm /etc/cron.d/oasis-login
grep "^ouser\." /etc/passwd|cut -d: -f1|while read OUSER; do
    userdel -r $OUSER
done
grep "^ouser\." /etc/group|cut -d: -f1|while read OUSER; do
    groupdel -r $OUSER
done
rm /etc/grid-security/grid-mapfile
# reverse yum install gsi-openssh-server gsissh-clients
yum -y remove globus-common globus-gsi-proxy-ssl libtool-ltdl
rm /etc/sysconfig/gsisshd /etc/gsissh/*
rmdir /etc/gsissh
# reverse yum install condor
yum -y remove blahp condor-classads perl-DateManip perl-XML-Simple globus-io globus-rsl gsoap voms globus-gssapi-error
yum -y remove oasis
rm /etc/iptables.d/60-local-oasis-login
service gociptables restart
service httpd stop
rm -f /var/www/html/stamp
yum -y remove httpd
yum -y remove pwgen
yum clean all
