#!/bin/bash
# /etc/rc.d/init.d/oasis-initclean
#chkconfig: - 88 12
#description: cleans up any leftover do_oasis_update locks
if [ "$1" = "start" ]; then
    LOCKPFX="/net/nas01/Public/"
    if [ "`uname -n|cut -d. -f1`" != oasis ]; then
	LOCKPFX=${LOCKPFX}itb_
    fi
    rm -f ${LOCKPFX}oasis_update_in_progress
fi
