#!/bin/bash
# /etc/rc.d/init.d/oasis-initclean
#chkconfig: - 88 12
#description: cleans up any leftover do_oasis_update locks
if [ "$1" = "start" ]; then
    LOCKPFX="/stage/locks/"
    if [ "`uname -n|cut -d. -f1`" != oasis ]; then
	LOCKPFX=${LOCKPFX}itb_
    fi
    rm -f ${LOCKPFX}oasis_update_in_progress ${LOCKPFX}oasis_update_requested_vo

    # Beginning in cvmfs-server-2.2.0 we need to mount all cvmfs mountpoints
    grep "CernVM-FS" /etc/fstab | awk '{print $2}' | while read M; do
	mount $M
    done
fi
