#!/bin/bash
# Install and configure all application software on oasis-login or
#   oasis-login-itb
# Written by Dave Dykstra 3-11-2015

cd

MYSHORTNAME="`hostname -s`"
case "$MYSHORTNAME" in
    oasis-login*);;
    *)  echo "Only run this on an oasis-login* machine"
	exit 2
	;;
esac

set -ex

# puppet sometimes returns error code if it is already running, ignore it
case "$MYSHORTNAME" in
    *-itb)
	puppet agent -t --environment=testing || true
	;;
    *)
	puppet agent -t || true
	;;
esac

ARCH=`arch`
OASISVER=2.1.22
OASISSUBVER=1.osg34.el6
OASISRPM=oasis-goc-$OASISVER-$OASISSUBVER.noarch.rpm
OASISRPM2=oasis-goc-login-$OASISVER-$OASISSUBVER.noarch.rpm

PATH="$PATH:/sbin:/usr/sbin"

# import OSG key because we'll be directly downloading oasis rpm
rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-OSG

# need yum-priorities to make OSG a higher priority than EPEL
yum -y install yum-priorities

# install condor
yum -y install condor
chkconfig condor on
service condor start

# install oasis
wget -N http://koji-hub.batlab.org/mnt/koji/packages/oasis-goc/$OASISVER/$OASISSUBVER/noarch/$OASISRPM
wget -N http://koji-hub.batlab.org/mnt/koji/packages/oasis-goc/$OASISVER/$OASISSUBVER/noarch/$OASISRPM2
yum -y install $OASISRPM $OASISRPM2
rm $OASISRPM $OASISRPM2

service gociptables restart

# mount /stage and /home/login directories
if ! grep -q "[ \t]/stage[ \t]" /etc/fstab; then
    echo "vm08:/oasis-share/stage /stage			nfs 	defaults	0 0" >>/etc/fstab
fi
mkdir -p /stage
if ! grep -q "[ \t]/home/login[ \t]" /etc/fstab; then
    echo "vm08:/oasis-share/home/login /home/login	nfs 	defaults	0 0" >>/etc/fstab
fi
mkdir -p /home/login

# need netfs to mount NFS at boot
chkconfig netfs on
service netfs start

# make convenience link
mkdir -p /cvmfs
ln -s /stage/oasis /cvmfs/oasis.opensciencegrid.org

# puppet is now configuring gsissh
# install gsisshd and gsissh clients (client needed for gsiscp)
#yum -y install gsi-openssh-server gsi-openssh-clients
#
#ln -s /etc/ssh/ssh_host_rsa_key /etc/gsissh/ssh_host_rsa_key
#ln -s /etc/ssh/ssh_host_rsa_key.pub /etc/gsissh/ssh_host_rsa_key.pub
#ln -s /etc/ssh/ssh_host_dsa_key /etc/gsissh/ssh_host_dsa_key
#ln -s /etc/ssh/ssh_host_dsa_key.pub /etc/gsissh/ssh_host_dsa_key.pub
#
#service sshd stop
#chkconfig sshd off
#service gsisshd start
#chkconfig gsisshd on

# for the status stamp
yum -y install httpd
chkconfig httpd on
service httpd start

# for generate_adduser
yum -y install pwgen

# add users
TMPF=/tmp/install-oasis-login-$$
/usr/share/oasis/generate_adduser >$TMPF.1
while read CMD; do
    USERNAME="`echo "$CMD"|awk '{print $3}'|sed 's/ouser.//'`"
    if [ ! -d /stage/oasis/$USERNAME ]; then
	# wasn't there before, let the cron create it
	continue
    fi
    uid="`stat -c '%u' /stage/oasis/$USERNAME`"
    gid="`stat -c '%g' /stage/oasis/$USERNAME`"
    groupadd -g $gid ouser.$USERNAME
    eval "`echo "$CMD"|sed "s/useradd/useradd -u $uid -g $gid/"`"
done <$TMPF.1
rm $TMPF.1

# add gridmap file
/usr/share/oasis/generate_gridmap >/etc/grid-security/grid-mapfile

# the user's want gcc to be able to compile
yum -y install gcc

# add cron entries
cat >>/etc/cron.d/oasis-login <<'xEOFx'
# Created by install script.  Will be recreated next reinstall.
*/5 * * * * root /usr/share/oasis/generate_adduser | bash
1-59/5 * * * * root cd /etc/grid-security; if /usr/share/oasis/generate_gridmap > grid-mapfile.tmp; then mv -f grid-mapfile.tmp grid-mapfile; fi
4,19,34,49 * * * * root   /usr/share/oasis/oasis_login_status >/dev/null 2>&1
xEOFx


rm -f /root/show_install_msg.sh

set +x

echo
echo "Installation of $MYSHORTNAME completed successfully at `date`"
echo
