#!/bin/bash
# Install and configure all application software on oasis-replica
#
# Mounts a directory on a large shared filesystem at /srv, and everything
#  that needs lots of space or needs to be retained across reinstalls is
#   put there.  In particular that is:
#   /srv/cvmfs -- the cvmfs replicas data default location
#   /etc/awstats/password-file -- the password used for uploading squid log
#	statistics to the WLCG squid monitor, copied from /srv/etc/awstats
#   /var/log/cvmfs -- logs from cvmfs crons, symlinked to /srv/log/cvmfs
#   /var/log/httpd -- apache logs, symlinked to /srv/log/httpd
#   /var/log/squid -- squid logs, symlinked to /srv/log/squid
#
# Initial version written by Dave Dykstra 2-4-2015

MYSHORTNAME="`echo ${1:-$(hostname -s)}|sed 's/hcc-//'`"
case "$MYSHORTNAME" in
    oasis-replica|oasis-replica-itb|cvmfs|cvmfs-itb);;
    *)  echo "Only run this on oasis-replica or oasis-replica-itb"
	exit 2
	;;
esac

case "`lsb_release -rs`" in
    7.*);;
    *)  echo "Only run this on el7"
        exit 2
        ;;
esac

set -ex

# Set ITBBOOTSTRAP to true to bootstrap oasis-replica-itb from
#   the production oasis and oasis-replica servers.  Then reinstall
#   from scatch again without the bootstrap to correct the server URLs.
ITBBOOTSTRAP=${ITBBOOTSTRAP:-false}

SCRIPTDIR="`dirname $0`"
if [ "$SCRIPTDIR" = "." ]; then
    SCRIPTDIR="`pwd`"
fi
cd

PATH="$PATH:/sbin"

# symlink /srv/cvmfs and /srv/etc to the big disk
for D in cvmfs etc; do 
    rm -rf /srv/$D
    ln -s /storage/$D /srv
done

# symlink important log directories to the big disk
for LOGD in cvmfs httpd squid; do
    mkdir -p /storage/log/$LOGD
    rm -rf /var/log/$LOGD
    ln -s /storage/log/$LOGD /var/log
done

# install cvmfs
yum -y install cvmfs cvmfs-server cvmfs-servermon

cp /etc/cvmfs/keys/opensciencegrid.org/opensciencegrid.org.pub /etc/cvmfs/keys
yum -y install mod_wsgi

echo -e "*\t\t-\tnofile\t\t16384" >>/etc/security/limits.conf
ulimit -n 16384

# install oasis
yum -y install oasis-goc oasis-goc-replica
systemctl enable oasis-replica-initclean

systemctl enable httpd
systemctl start httpd

# install frontier-squid & frontier-awstats
yum -y install frontier-squid frontier-awstats

# squid log dir has to be owned by squid user id
chown squid:squid /srv/log/squid

# install frontier-awstats password if available
APWFILE=/srv/etc/awstats/password-file
if [ -f $APWFILE ]; then
    cp $APWFILE /etc/awstats
    chown squid:squid /etc/awstats/password-file
fi

# need nfslock for the repos to be on NFS
systemctl enable nfslock
systemctl start nfslock

# on itb read from oasis-itb unless bootstrapping
ITB=""
case $MYSHORTNAME in
    *-itb)
	if ! $ITBBOOTSTRAP; then
	    ITB="-itb"
	fi
	;;
esac

REPOURLS=""
for REPO in oasis config-osg; do
    REPOURLS="$REPOURLS http://oasis$ITB.opensciencegrid.org:8000/cvmfs/$REPO.opensciencegrid.org"
done
NONOIMREPOURLS="$REPOURLS"

# add repos hosted on our stratum 0
for URL in $REPOURLS; do
    add_osg_repository -a "$URL"
done

# add other repos not registered in OIM
REPOURLS="http://cvmfs-stratum0.gridpp.rl.ac.uk:8000/cvmfs/config-egi.egi.eu"
NONOIMREPOURLS="$NONOIMREPOURLS $REPOURLS"
for URL in $REPOURLS; do
    if $ITBBOOTSTRAP; then
	add_osg_repository -a "http://oasis-replica.opensciencegrid.org:8080/cvmfs/`basename $URL`"
    else
	add_osg_repository -a "$URL"
    fi
done

# Add repos registered in OIM.  It's OK if these fail because they will
#  be added later by the generate_replicas cron.
OIMREPOURLS="`print_osg_repos -u`"
for URL in $OIMREPOURLS; do
    if $ITBBOOTSTRAP; then
	add_osg_repository -a "http://oasis-replica.opensciencegrid.org:8080/cvmfs/`basename $URL`" || true
    else
	add_osg_repository -a "$URL" || true
    fi
done

# make copies of .cvmfswhitelists from oasis
mkdir -p /oasissrv/cvmfs
/usr/share/oasis/replicate_whitelists

# do initial snapshots for those repos that need it
for URL in $NONOIMREPOURLS; do
    REPO="`basename $URL`"
    cvmfs_server snapshot $REPO
done

for URL in $OIMREPOURLS; do
    REPO="`basename $URL`"
    if [ ! -f /srv/cvmfs/$REPO/.cvmfspublished ]; then
	if ! cvmfs_server snapshot $REPO; then
	    # initial snapshot failed so remove the repo so it can be
	    #  added later by generate_replicas
	    cvmfs_server rmfs -f $REPO || true
	fi
    fi
done

# start squid last after everything is ready, because that makes
#   the service available
systemctl enable frontier-squid
systemctl start frontier-squid

# finish installation, create 'installed' file used by /etc/cron.d/cvmfs
mkdir -p /var/log/cvmfs /var/lib/oasis
date >/var/lib/oasis/installed

set +x
echo 
echo "Installation of $MYSHORTNAME completed successfully at `date`"
