#!/bin/bash
# Install and configure all application software on oasis or oasis-itb
#
# Mounts a directory on a large shared filesystem at /srv, and everything
#  that needs lots of space or needs to be retained across reinstalls is
#   put there.  In particular that is:
#   /srv/cvmfs -- the cvmfs repository data default location
#   /etc/cvmfs/keys/oasis.opensciencegrid.org.{pub|masterkey} -- the itb
#       version of these is stored in /srv/etc/cvmfs (the production version
# 	of the masterkey is stored offline accessible only to GOC staff)
#   /cvmfs/opensciencegrid.org/.cvmfsdirtab -- copied from /srv/etc/repo
#   /var/log/httpd -- apache logs, symlinked to /srv/log/httpd
#   /var/log/oasis -- logs from oasis crons, symlinked to /srv/log/oasis
#   /var/spool/cvmfs/oasis.opensciencegrid.org/scratch -- place for files prior
#	to publish, mounted from /srv/spool/oasis.opensciencegrid.org/scratch
#
# Initial version written by Dave Dykstra 2-26-2015

MYSHORTNAME="`hostname -s`"
case "$MYSHORTNAME" in
    oasis|oasis-itb);;
    *)  echo "Only run this on oasis or oasis-itb"
	exit 2
	;;
esac

set -ex

SCRIPTDIR="`dirname $0`"
if [ "$SCRIPTDIR" = "." ]; then
    SCRIPTDIR="`pwd`"
fi
cd

# puppet sometimes returns error code if it is already running, ignore it
case "$MYSHORTNAME" in
    *-itb)
	puppet agent -t --environment=testing || true
	;;
    *)
	puppet agent -t || true
	;;
esac

ARCH=`arch`
AUFSRPM=aufs-0.20090202.cvs-6.sl5.src.rpm
CVMFSRELRPM=cvmfs-release-2-4.el5.noarch.rpm
CVMFSVER=2.1.20
CVMFSRPM=cvmfs-$CVMFSVER-1.el5.$ARCH.rpm
CVMFSSERVERRPM=cvmfs-server-$CVMFSVER-1.el5.$ARCH.rpm
CVMFSCONFIGRPM=cvmfs-config-default-1.1-1.noarch.rpm
OASISVER=2.1.0
OASISSUBVER=1.osg32.el5
OASISRPM=oasis-goc-$OASISVER-$OASISSUBVER.noarch.rpm
OASISRPM2=oasis-goc-zero-$OASISVER-$OASISSUBVER.noarch.rpm

PATH="$PATH:/sbin"

# import OSG key because we'll be directly downloading oasis rpm
rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-OSG

# download, build, and install aufs
wget -q -N "http://ftp.scientificlinux.org/linux/scientific/5x/SRPMS/SL/$AUFSRPM"
mkdir -p /usr/src/redhat/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
rpm -i $AUFSRPM
rm $AUFSRPM
# note: the kernel-devel install may not be needed; it's not removed in
#  uninstall but try to install it because it's not guaranteed to be there
yum install -y rpm-build kernel-devel-`uname -r` gcc
rpmbuild -ba --target $ARCH --define "kernel `uname -r`" /usr/src/redhat/SPECS/aufs.spec
rpm -iv /usr/src/redhat/RPMS/$ARCH/*aufs*.rpm

# install aufs postupdate script so it will get rebuilt when kernel is rebuilt
mkdir -p /opt/etc/osupdate.d
cp $SCRIPTDIR/aufs.postupdate /opt/etc/osupdate.d
# and run it now in case an osupdate happened before this install
/opt/etc/osupdate.d/aufs.postupdate

# create srv directory if it isn't there yet
NETSRVDIR="/net/vm08/oasis-share/srv/$MYSHORTNAME"
if [ ! -d $NETSRVDIR ]; then
    mkdir $NETSRVDIR
    setfacl -b $NETSRVDIR
    chmod 755 $NETSRVDIR
fi

# mount srv directory permanently at /srv
if ! grep -q "[ \t]/srv[ \t]" /etc/fstab; then
    # the sed changes "/net/vm08" in $NETSRVDIR to "vm08:"
    echo "`echo $NETSRVDIR|sed 's,/net/\([^/]*\),\1:,'` /srv	nfs 	defaults 	0 0" >>/etc/fstab
fi
mkdir -p /srv

# need netfs to mount NFS at boot
chkconfig netfs on
# The chkconfig on by itself isn't enough, because /etc/resolv.conf listens
#  only on 127.0.0.1 and the server doesn't start until late.  This works
#  around it by starting the local dns caching server earlier.
ln -s /etc/rc3.d/S99dnsmasq /etc/rc3.d/S24dnsmasq
service netfs start

# create symlinks for important log directories out to the NAS
for LOGD in oasis httpd; do
    mkdir -p /srv/log/$LOGD
    rm -rf /var/log/$LOGD
    ln -s /srv/log/$LOGD /var/log
done

# install cvmfs
curl -O https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/$CVMFSRELRPM
rpm -i $CVMFSRELRPM
rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-CernVM
rpm -e cvmfs-release
rm $CVMFSRELRPM
curl -O https://ecsft.cern.ch/dist/cvmfs/cvmfs-$CVMFSVER/$CVMFSRPM
curl -O https://ecsft.cern.ch/dist/cvmfs/cvmfs-$CVMFSVER/$CVMFSSERVERRPM
curl -O https://ecsft.cern.ch/dist/cvmfs/cvmfs-config/$CVMFSCONFIGRPM
CVRPMS="$CVMFSRPM $CVMFSSERVERRPM $CVMFSCONFIGRPM"
yum -y install $CVRPMS
rm $CVRPMS
cp /etc/cvmfs/keys/opensciencegrid.org/opensciencegrid.org.pub /etc/cvmfs/keys
# move /var/spool/cvmfs to /usr/spool because /var is too small for cache & tmp
rm -rf /usr/spool/cvmfs
mkdir -p /usr/spool
mv /var/spool/cvmfs /usr/spool
ln -s /usr/spool/cvmfs /var/spool

echo -e "*\t\t-\tnofile\t\t16384" >>/etc/security/limits.conf
ulimit -n 16384

cat >>/etc/sysctl.conf <<xEOFx
# Controls maximum listen() backlog for apache.  Added by install script.
net.core.somaxconn = 1024
xEOFx
sysctl -w net.core.somaxconn=1024

mkdir -p /srv

# install oasis
wget -N http://koji-hub.batlab.org/mnt/koji/packages/oasis-goc/$OASISVER/$OASISSUBVER/noarch/$OASISRPM
wget -N http://koji-hub.batlab.org/mnt/koji/packages/oasis-goc/$OASISVER/$OASISSUBVER/noarch/$OASISRPM2
yum -y install $OASISRPM $OASISRPM2
rm $OASISRPM $OASISRPM2
chkconfig oasis-initclean on

chkconfig httpd on
service httpd start

service gociptables restart

# need nfslock for the repos to be on NFS
chkconfig nfslock on
service nfslock start

if [ -d /srv/cvmfs/oasis.opensciencegrid.org ]; then
    # old repository data present.  save it for later
    mkdir -p /srv/cvmfs.save
    mv /srv/cvmfs/oasis.opensciencegrid.org /srv/cvmfs.save
fi

# Use this new code with cvmfs-server-2.2.0
# Then the code saving /srv/cvmfs.save above and restoring below can also
#   be deleted.
#if [ -d /srv/cvmfs/oasis.opensciencegrid.org ]; then
#    # Old oasis repository data present.  Use import instead of mkfs.
#    # It expects a masterkey and pub to be present from before.
#    # Use ITB key for now and replace later.
#    for KEY in pub masterkey; do
#	cp /srv/etc/cvmfs/oasis-itb.opensciencegrid.org.$KEY /etc/cvmfs/oasis.opensciencegrid.org.$KEY
#	chown oasis /etc/cvmfs/oasis.opensciencegrid.org.$KEY
#    done
#    cvmfs_server import -r -t -o oasis oasis.opensciencegrid.org
#else
    # add oasis repo
    CVMFS_AUFS_WARNING=false cvmfs_server mkfs -m -o oasis oasis.opensciencegrid.org
#fi
echo "CVMFS_AUFS_WARNING=false" >>/etc/cvmfs/repositories.d/oasis.opensciencegrid.org/server.conf
echo "CVMFS_IGNORE_XDIR_HARDLINKS=true" >>/etc/cvmfs/repositories.d/oasis.opensciencegrid.org/server.conf
echo "CVMFS_AUTO_TAG=false" >>/etc/cvmfs/repositories.d/oasis.opensciencegrid.org/server.conf
rm -f /etc/httpd/conf.d/cvmfs.oasis.opensciencegrid.org.conf

# move scratch dir to attached storage
umount /cvmfs/oasis.opensciencegrid.org
rm -rf /srv/spool/oasis.opensciencegrid.org/scratch
mkdir -p /srv/spool/oasis.opensciencegrid.org
mv /var/spool/cvmfs/oasis.opensciencegrid.org/scratch /srv/spool/oasis.opensciencegrid.org
mkdir /var/spool/cvmfs/oasis.opensciencegrid.org/scratch
# the second sed changes "/net/hostname" in $NETSRVDIR to "hostname:"
sed -i -e "/^cvmfs2#oasis/i`echo $NETSRVDIR|sed 's,/net/\([^/]*\),\1:,'`/spool/oasis.opensciencegrid.org/scratch /var/spool/cvmfs/oasis.opensciencegrid.org/scratch nfs defaults 0 0 # added by install-oasis" /etc/fstab
mount /var/spool/cvmfs/oasis.opensciencegrid.org/scratch
mount /cvmfs/oasis.opensciencegrid.org

# on itb install the saved itb pub & master key
case $MYSHORTNAME in
    *-itb)
	if [ ! -f /srv/etc/cvmfs/oasis-itb.opensciencegrid.org.pub ]; then
	    # make a copy from production srv directory of itb pub and masterkey
	    PRODSRVDIR="`echo $NETSRVDIR|sed 's/-itb//'`"
	    mkdir -p /srv/etc/cvmfs
	    cp $PRODSRVDIR/etc/cvmfs/oasis-itb.opensciencegrid.org.* /srv/etc/cvmfs
	fi
	for KEY in pub masterkey; do
	    cp /srv/etc/cvmfs/oasis-itb.opensciencegrid.org.$KEY /etc/cvmfs/keys/oasis.opensciencegrid.org.$KEY
	done
	cvmfs_server resign
	;;
esac

RUNUSER="runuser -s /bin/bash oasis -c"

REPONAME=oasis.opensciencegrid.org
if [ -d /srv/cvmfs.save/$REPONAME ]; then
    # restore old repository data
    # update the old .cvmfspublished with new certificate hash
    CERTHASH="`cat -v /srv/cvmfs/$REPONAME/.cvmfspublished|sed -n '/^X/{s/^X//p;q}'`"
    $RUNUSER "cd /srv/cvmfs.save/$REPONAME; cat -v .cvmfspublished | \
	    sed 's/^X.*/X'$CERTHASH'/;/^--/q' > .cvmfspublished.unsigned"
    CERTPATH="`echo $CERTHASH|sed 's,^\(..\),\1/,'`X"
    $RUNUSER "cp /srv/cvmfs/$REPONAME/data/$CERTPATH /srv/cvmfs.save/$REPONAME/data/$CERTPATH"
    rm -rf /srv/cvmfs/$REPONAME
    mv /srv/cvmfs.save/$REPONAME /srv/cvmfs/$REPONAME
    rmdir /srv/cvmfs.save
    UPSTREAM="`sed -n 's/^CVMFS_UPSTREAM_STORAGE=//p' /etc/cvmfs/repositories.d/$REPONAME/server.conf`"
    $RUNUSER "cd /srv/cvmfs/$REPONAME; cvmfs_swissknife sign -c /etc/cvmfs/keys/$REPONAME.crt -k /etc/cvmfs/keys/$REPONAME.key -n $REPONAME -m .cvmfspublished.unsigned -t /var/spool/cvmfs/$REPONAME/tmp -r $UPSTREAM; rm -f cvmfspublished.unsigned"
    cvmfs_server resign

    # sync up the view in /cvmfs/oasis.opensciencegrid.org with
    #   new underlying data
    $RUNUSER "cvmfs_server transaction"
    $RUNUSER "cvmfs_server publish"
fi

# Manage repository content special content

$RUNUSER "cvmfs_server transaction"

if [ -f /cvmfs/oasis.opensciencegrid.org/new_repository ]; then
    # clean out initial file
    rm /cvmfs/oasis.opensciencegrid.org/new_repository
fi

# make sure there's a .cvmfsdirtab
DIRTAB=/srv/etc/repo/.cvmfsdirtab
if [ ! -f $DIRTAB ]; then
    case $MYSHORTNAME in
	*-itb)
	    # make a copy from production
	    SRCDIRTAB="`echo $NETSRVDIR|sed 's/-itb//'``echo $DIRTAB|sed 's,^/srv,,'`"
	    mkdir -p `dirname $DIRTAB`
	    cp $SRCDIRTAB $DIRTAB
	    ;;
    esac
fi
if [ ! -f /cvmfs/oasis.opensciencegrid.org/.cvmfsdirtab ]; then
    $RUNUSER "cp $DIRTAB /cvmfs/oasis.opensciencegrid.org"
fi

if [ ! -L /cvmfs/oasis.opensciencegrid.org/cmssoft/cms ]; then
    # create special cms symlink
    $RUNUSER "mkdir -p /cvmfs/oasis.opensciencegrid.org/cmssoft"
    $RUNUSER "ln -s /cvmfs/cms.cern.ch /cvmfs/oasis.opensciencegrid.org/cmssoft/cms"
fi

if [ ! -L /cvmfs/oasis.opensciencegrid.org/osg-software/osg-wn-client ]; then
    # create special osg-software symlink
    $RUNUSER "mkdir -p /cvmfs/oasis.opensciencegrid.org/osg-software"
    $RUNUSER "ln -s /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client /cvmfs/oasis.opensciencegrid.org/osg-software/osg-wn-client"
fi

sleep 2 # when auto tagging is on, cvmfs-2.1.20 complains if two publishes done in the same second
$RUNUSER "cvmfs_server publish"

# add cron entries
mkdir -p /var/log/oasis
cat >/etc/cron.d/oasis <<'xEOFx'
# Created by install script.  Will be recreated next reinstall.
* * * * *   root   /usr/share/oasis/do_oasis_update
*/3 * * * * root   /usr/share/oasis/oasis_status_stamp >/dev/null 2>&1
xEOFx
case $MYSHORTNAME in
    *-itb)
	echo "0 7 1,15 * * root  /usr/bin/resign_osg_whitelist >/dev/null 2>&1" >>/etc/cron.d/oasis
	;;
esac

# request updates on all vos that have changed

LOCKPFX=/net/nas01/Public/
case "$MYSHORTNAME" in
    *-itb) LOCKPFX=${LOCKPFX}itb_;;
esac
rm -f ${LOCKPFX}vo_update_requested # sometimes this doesn't get cleaned up
/usr/share/oasis/update_oasis_vos

case "$MYSHORTNAME" in
    *-itb) 
	# on itb also update the vos once an hour if they have changed
	cat >>/etc/cron.d/oasis <<xEOFx
1 * * * *   root   /usr/share/oasis/update_oasis_vos >>/var/log/oasis/voupdates.log 2>&1
xEOFx
	;;
esac

# Update the publication revision to be 100 greater than the previous revision.
# Read it from FNAL stratum 1 because oasis-replica may be down for a common
#  upgrade.
PREVREVISION="`wget -qO- http://cvmfs.fnal.gov:8000/cvmfs/oasis.opensciencegrid.org/.cvmfspublished|cat -v|sed -n '/^S/{s/^S//p;q;}'`"
let PREVREVISION+=100
CURREVISION="`cat -v /srv/cvmfs/oasis.opensciencegrid.org/.cvmfspublished|sed -n '/^S/{s/^S//p;q;}'`"

if [ "$PREVREVISION" -gt "$CURREVISION" ]; then
    $RUNUSER "cvmfs_server transaction"
    $RUNUSER "cvmfs_server publish -n $PREVREVISION"
fi

set +x

# add the signed external repositories whitelists from oasis-replica
# this is safer than reading from the original sources, in case one is down
for REPO in config-egi.egi.eu `print_osg_repos`; do
    if [ ! -f /srv/cvmfs/$REPO/.cvmfswhitelist ]; then
	URL="http://oasis-replica.opensciencegrid.org:8000/cvmfs/$REPO/.cvmfswhitelist"
	echo "Adding whitelist from $URL"
	mkdir -p /srv/cvmfs/$REPO
	wget -q -O/srv/cvmfs/$REPO/.cvmfswhitelist $URL
    fi
done

case $MYSHORTNAME in
    *-itb) resign_osg_whitelist;;
esac

echo
echo "Installation of $MYSHORTNAME completed successfully at `date`"
echo
case $MYSHORTNAME in
    *-itb);;
    *)  # on prod remove the temporary masterkey and install official public key
	rm /etc/cvmfs/keys/oasis.opensciencegrid.org.masterkey
	cp /etc/cvmfs/keys/opensciencegrid.org.pub /etc/cvmfs/keys/oasis.opensciencegrid.org.pub
	echo "Now temporarily install /etc/cvmfs/keys/oasis.opensciencegrid.org.masterkey"
	echo "   and run resign_osg_whitelist"
esac
