#!/bin/bash
# Uninstall everything installed by install-oasis-login, to facilitate
#  testing install-oasis-login without creating a new VM from scratch
# Written by Dave Dykstra 3-11-2015

cd

case "`uname -n`" in
    oasis-login*);;
    *)  echo "Only run this on an oasis-login* machine"
	exit 2
	;;
esac

case $0 in
    /tmp/*);;
    *)  # get out of NFS filesystem because netfs stop kills it
	cp $0 /tmp
	exec /tmp/uninstall-oasis-login
	;;
esac

case `lsb_release -a|sed -n 's/Release:[ \t]*\([0-9]\)*.*/\1/p'` in
    5)  EXTRACONDORPKG=perl-DateManip
	EXTRAHTTPDPKGS=
	GCCPKGS=gcc
	;;
    6)  EXTRACONDORPKG=
	EXTRAHTTPDPKGS="apr-util-ldap httpd-tools"
	GCCPKGS="ppl mpfr"
	;;
    *)  echo "Not running on el5 or el6"
        exit 2
	;;
esac

set -x
PATH="$PATH:/sbin:/usr/sbin"
rm /etc/cron.d/oasis-login
#service gsisshd stop
#chkconfig gsisshd off
#service sshd start
#chkconfig sshd on
service netfs stop # umounts nfs-mounted filesystems
chkconfig netfs off
sed -i '/[ \t]\/stage[ \t]/d' /etc/fstab
sed -i '/[ \t]\/home\/login[ \t]/d' /etc/fstab
rm /cvmfs/oasis.opensciencegrid.org
rmdir /stage /home/login /cvmfs
for r in `rpm -qa|grep gpg-pubkey|sed 's/\.(none)//'|sort -u`; do
    rpm --allmatches -e $r
done
grep "^ouser\." /etc/passwd|cut -d: -f1|while read OUSER; do
    userdel $OUSER
done
grep "^ouser\." /etc/group|cut -d: -f1|while read OUSER; do
    groupdel $OUSER
done
rm /etc/grid-security/grid-mapfile
yum -y remove $GCCPKGS
yum -y remove yum-priorities
# reverse yum install gsi-openssh-server gsissh-clients
#yum -y remove globus-common globus-gsi-proxy-ssl libtool-ltdl
#rm /etc/gsissh/*
#rmdir /etc/gsissh
# reverse yum install condor
yum -y remove blahp condor-classads $EXTRACONDORPKG perl-XML-Simple globus-io globus-rsl gsoap voms globus-gssapi-error
yum -y remove oasis-goc oasis-goc-login
rm -rf /etc/oasis
service gociptables restart
service httpd stop
rm -f /var/www/html/stamp
yum -y remove httpd $EXTRAHTTPDPKGS
yum -y remove pwgen
yum clean all
yum clean expire-cache  # temporarily until yum is updated
