#!/usr/bin/env python

import os
import sys
from oasispackage.oasisprobes import Probes

# get the VO from inputs  ?? temporary solution ??
vo = sys.argv[1]

probes = Probes()
probes.vo = vo

# 1st run the default OASIS probes
conffile = '/etc/oasis/oasisprobes.conf'
if os.path.exists(conffile):
    probes.conffile = conffile
    rc = probes.run()
    if rc != 0:
        sys.exit(rc)
    
# 2nd run the specific VO probes
conffile = '/etc/oasis/oasisprobes.d/%s.conf' %vo
if os.path.exists(conffile):
    probes.conffile = conffile
    rc = probes.run()
    sys.exit(rc)

# if no config file at all...
sys.exit(0)
