#!/bin/bash
# update all oasis VOs that have changed

LOCKPFX=/net/nas01/Public/
case "`hostname -s`" in
    *-itb) LOCKPFX=${LOCKPFX}itb_;;
esac

for URL in `print_osg_repos -u`; do
    REPO="`basename $URL`"
    if [ ! -d /srv/cvmfs/$REPO ]; then
	echo "Adding repository $REPO at `date`"
	add_osg_repository $URL
    fi
done

for VO in `/usr/share/oasis/print_oasis_vonames`; do
    if [ ! -f /net/nas01/Public/ouser.$VO/update.details ]; then
	# skip because it hasn't been published yet
	continue
    fi
    if cmp /net/nas01/Public/ouser.$VO/update.details /cvmfs/oasis.opensciencegrid.org/$VO/update.details >/dev/null 2>&1; then
	# already up to date, nothing to do
	continue
    fi
    if [ -f ${LOCKPFX}vo_update_requested ]; then
	echo "Skipping update for $VO because `cat ${LOCKPFX}vo_update_requested` update in progress"
	exit 1
    fi
    echo "Requesting update for $VO at `date`"
    echo $VO >${LOCKPFX}vo_update_requested
    # this waits for the request to complete
    /usr/share/oasis/request_oasis_update
    rm ${LOCKPFX}vo_update_requested
done
