#!/bin/env python


# FIXME: needs improvements
#   -- maybe commands is not the best choice
#   -- print meaningful error message when RC != 0

import commands

def main(options):

    st, out = commands.getstatusoutput('service oasisd status')
    print out
    return st


if __name__ == '__main__':
    rc = main(sys.argv[1:])
    sys.exit(rc)


# ================================================================




