#!/bin/bash

# this only runs from cron so a very simple lock file in RAM is sufficient
mkdir -p /var/run/cvmfs
LOCKFILE=/var/run/cvmfs/generating_whitelists
if [ -f $LOCKFILE ]; then
    exit
fi
echo $$ >$LOCKFILE

OLDSOURCE=""
(
echo "addcmd add_osg_repository @url@/cvmfs/@fqrn@"
echo "remcmd remove_osg_repository -f @fqrn@"
echo "keysource cvmfs-contrib/config-repo/master/etc/cvmfs/keys"
print_osg_repos -u|sed 's,\([^/]*/[^/]*/[^/]*\)/cvmfs/\(.*\),\1 \2,'| \
        while read SOURCE REPO; do
    if [ "$SOURCE" != "$OLDSOURCE" ]; then
        echo source $SOURCE
        OLDSOURCE=$SOURCE
    fi
    echo repos $REPO
done
) | manage-replicas -c -f /dev/stdin

rm -f $LOCKFILE
