#!/bin/bash
# NOTE: this is no longer maintained or up to date
#
# Uninstall everything installed by install-oasis, to facilitate
#  testing install-oasis without creating a new VM from scratch
# Written by Dave Dykstra 2-26-2015

# this is currently set up to uninstall on either el5 or el7

case "`uname -n`" in
    oasis.*|oasis-itb.*);;
    *)  echo "Only run this on oasis or oasis-itb"
	exit 2
	;;
esac

set -x
case $0 in
    /tmp/*);;
    *)  # get out of NFS filesystem because netfs stop kills it
	cp $0 /tmp
	exec /tmp/uninstall-oasis
	;;
esac
cd
PATH="$PATH:/sbin"
rm -f /etc/cron.d/oasis-itb
rm -rf /var/lib/oasis
killall rsync
killall cvmfs_swissknife
service httpd stop
umount /srv
umount /stage
service netfs stop
chkconfig netfs off
sed -i '/[ \t]\/srv[ \t]/d' /etc/fstab
sed -i '/[ \t]\/stage[ \t]/d' /etc/fstab
rmdir /srv /stage
if [ -d /srv ]; then
    echo "/srv still exists!"
    exit 1
fi
chkconfig oasis-initclean off
yum -y remove oasis-goc oasis-goc-zero
cvmfs_server rmfs -f oasis.opensciencegrid.org # removes partially
umount /var/spool/cvmfs/oasis.opensciencegrid.org/scratch
cvmfs_server rmfs -f oasis.opensciencegrid.org # finishes the remove
cvmfs_server rmfs -f config-osg.opensciencegrid.org
rm /var/spool/cvmfs
rm -rf /usr/spool/cvmfs
rmdir /usr/spool
sed -i -e '/added by install-oasis/d' /etc/fstab
rm -rf /var/spool/cvmfs/*
rm /opt/etc/osupdate.d/aufs.postupdate
rm -rf /usr/src/redhat/*/aufs* /usr/src/redhat/RPMS/*/*aufs*
rmdir /usr/src/redhat/RPMS/* /usr/src/redhat/* /usr/src/redhat
yum -y remove elfutils-libs xz-libs gcc aufs kernel-module-aufs
rm -rf /var/log/oasis
service httpd stop
sed -i -e '/Added by install/d' -e '/^net.core.somaxconn/d' /etc/sysctl.conf
sysctl -w net.core.somaxconn=128
rm -f /var/www/html/stamp
rpm -e cvmfs-release
for r in `rpm -qa|grep gpg-pubkey|sed 's/\.(none)//'|sort -u`; do
    rpm --allmatches -e $r
done
yum -y remove httpd fuse fuse-libs cvmfs-config gdb
rm -rf /var/log/httpd
sed -i '/nofile.*16384/d' /etc/security/limits.conf
rm -rf /etc/cvmfs
service gociptables restart
service iptables restart
yum clean all
yum clean expire-cache  # temporarily until yum is updated
service nfslock stop
chkconfig nfslock off
