#!/bin/env python


# FIXME: needs improvements
#   -- maybe commands is not the best choice
#   -- print meaningful error message when RC != 0
#   -- start the daemon only on a host that makes sense (for example, login host it does not)

import commands

def main(options):

    st, out = commands.getstatusoutput('service oasisd restart')
    return st


if __name__ == '__main__':
    rc = main(sys.argv[1:])
    sys.exit(rc)


# ================================================================




